/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppApplicationsRouteImport } from './routes/_app.applications'
import { Route as AppBlankRouteImport } from './routes/_app.blank'
import { Route as AppCommissionsRouteImport } from './routes/_app.commissions'
import { Route as AppDisbursementsRouteImport } from './routes/_app.disbursements'
import { Route as AppLeadsRouteImport } from './routes/_app.leads'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppSanctionsRouteImport } from './routes/_app.sanctions'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSourcingPartnersRouteImport } from './routes/_app.sourcing-partners'
import { Route as AppTeamRouteImport } from './routes/_app.team'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicationsRoute = AppApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AppRoute,
} as any)
const AppBlankRoute = AppBlankRouteImport.update({
  id: '/blank',
  path: '/blank',
  getParentRoute: () => AppRoute,
} as any)
const AppCommissionsRoute = AppCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => AppRoute,
} as any)
const AppDisbursementsRoute = AppDisbursementsRouteImport.update({
  id: '/disbursements',
  path: '/disbursements',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSanctionsRoute = AppSanctionsRouteImport.update({
  id: '/sanctions',
  path: '/sanctions',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSourcingPartnersRoute = AppSourcingPartnersRouteImport.update({
  id: '/sourcing-partners',
  path: '/sourcing-partners',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/applications': typeof AppApplicationsRoute
  '/blank': typeof AppBlankRoute
  '/commissions': typeof AppCommissionsRoute
  '/disbursements': typeof AppDisbursementsRoute
  '/leads': typeof AppLeadsRoute
  '/reports': typeof AppReportsRoute
  '/sanctions': typeof AppSanctionsRoute
  '/settings': typeof AppSettingsRoute
  '/sourcing-partners': typeof AppSourcingPartnersRoute
  '/team': typeof AppTeamRoute
}
export interface FileRoutesByTo {
  '/applications': typeof AppApplicationsRoute
  '/blank': typeof AppBlankRoute
  '/commissions': typeof AppCommissionsRoute
  '/disbursements': typeof AppDisbursementsRoute
  '/leads': typeof AppLeadsRoute
  '/reports': typeof AppReportsRoute
  '/sanctions': typeof AppSanctionsRoute
  '/settings': typeof AppSettingsRoute
  '/sourcing-partners': typeof AppSourcingPartnersRoute
  '/team': typeof AppTeamRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/applications': typeof AppApplicationsRoute
  '/_app/blank': typeof AppBlankRoute
  '/_app/commissions': typeof AppCommissionsRoute
  '/_app/disbursements': typeof AppDisbursementsRoute
  '/_app/leads': typeof AppLeadsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/sanctions': typeof AppSanctionsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/sourcing-partners': typeof AppSourcingPartnersRoute
  '/_app/team': typeof AppTeamRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/blank'
    | '/commissions'
    | '/disbursements'
    | '/leads'
    | '/reports'
    | '/sanctions'
    | '/settings'
    | '/sourcing-partners'
    | '/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/applications'
    | '/blank'
    | '/commissions'
    | '/disbursements'
    | '/leads'
    | '/reports'
    | '/sanctions'
    | '/settings'
    | '/sourcing-partners'
    | '/team'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/applications'
    | '/_app/blank'
    | '/_app/commissions'
    | '/_app/disbursements'
    | '/_app/leads'
    | '/_app/reports'
    | '/_app/sanctions'
    | '/_app/settings'
    | '/_app/sourcing-partners'
    | '/_app/team'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/applications': {
      id: '/_app/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AppApplicationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/blank': {
      id: '/_app/blank'
      path: '/blank'
      fullPath: '/blank'
      preLoaderRoute: typeof AppBlankRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/commissions': {
      id: '/_app/commissions'
      path: '/commissions'
      fullPath: '/commissions'
      preLoaderRoute: typeof AppCommissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/disbursements': {
      id: '/_app/disbursements'
      path: '/disbursements'
      fullPath: '/disbursements'
      preLoaderRoute: typeof AppDisbursementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sanctions': {
      id: '/_app/sanctions'
      path: '/sanctions'
      fullPath: '/sanctions'
      preLoaderRoute: typeof AppSanctionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sourcing-partners': {
      id: '/_app/sourcing-partners'
      path: '/sourcing-partners'
      fullPath: '/sourcing-partners'
      preLoaderRoute: typeof AppSourcingPartnersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppApplicationsRoute: typeof AppApplicationsRoute
  AppBlankRoute: typeof AppBlankRoute
  AppCommissionsRoute: typeof AppCommissionsRoute
  AppDisbursementsRoute: typeof AppDisbursementsRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSanctionsRoute: typeof AppSanctionsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSourcingPartnersRoute: typeof AppSourcingPartnersRoute
  AppTeamRoute: typeof AppTeamRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApplicationsRoute: AppApplicationsRoute,
  AppBlankRoute: AppBlankRoute,
  AppCommissionsRoute: AppCommissionsRoute,
  AppDisbursementsRoute: AppDisbursementsRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSanctionsRoute: AppSanctionsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSourcingPartnersRoute: AppSourcingPartnersRoute,
  AppTeamRoute: AppTeamRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
