/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as CommissionsRouteImport } from './routes/commissions'
import { Route as DisbursementsRouteImport } from './routes/disbursements'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SanctionsRouteImport } from './routes/sanctions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SourcingPartnersRouteImport } from './routes/sourcing-partners'
import { Route as TeamRouteImport } from './routes/team'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const CommissionsRoute = CommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => rootRouteImport,
} as any)
const DisbursementsRoute = DisbursementsRouteImport.update({
  id: '/disbursements',
  path: '/disbursements',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SanctionsRoute = SanctionsRouteImport.update({
  id: '/sanctions',
  path: '/sanctions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcingPartnersRoute = SourcingPartnersRouteImport.update({
  id: '/sourcing-partners',
  path: '/sourcing-partners',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/commissions': typeof CommissionsRoute
  '/disbursements': typeof DisbursementsRoute
  '/leads': typeof LeadsRoute
  '/reports': typeof ReportsRoute
  '/sanctions': typeof SanctionsRoute
  '/settings': typeof SettingsRoute
  '/sourcing-partners': typeof SourcingPartnersRoute
  '/team': typeof TeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/commissions': typeof CommissionsRoute
  '/disbursements': typeof DisbursementsRoute
  '/leads': typeof LeadsRoute
  '/reports': typeof ReportsRoute
  '/sanctions': typeof SanctionsRoute
  '/settings': typeof SettingsRoute
  '/sourcing-partners': typeof SourcingPartnersRoute
  '/team': typeof TeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/commissions': typeof CommissionsRoute
  '/disbursements': typeof DisbursementsRoute
  '/leads': typeof LeadsRoute
  '/reports': typeof ReportsRoute
  '/sanctions': typeof SanctionsRoute
  '/settings': typeof SettingsRoute
  '/sourcing-partners': typeof SourcingPartnersRoute
  '/team': typeof TeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/commissions'
    | '/disbursements'
    | '/leads'
    | '/reports'
    | '/sanctions'
    | '/settings'
    | '/sourcing-partners'
    | '/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/commissions'
    | '/disbursements'
    | '/leads'
    | '/reports'
    | '/sanctions'
    | '/settings'
    | '/sourcing-partners'
    | '/team'
  id:
    | '__root__'
    | '/'
    | '/applications'
    | '/commissions'
    | '/disbursements'
    | '/leads'
    | '/reports'
    | '/sanctions'
    | '/settings'
    | '/sourcing-partners'
    | '/team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsRoute: typeof ApplicationsRoute
  CommissionsRoute: typeof CommissionsRoute
  DisbursementsRoute: typeof DisbursementsRoute
  LeadsRoute: typeof LeadsRoute
  ReportsRoute: typeof ReportsRoute
  SanctionsRoute: typeof SanctionsRoute
  SettingsRoute: typeof SettingsRoute
  SourcingPartnersRoute: typeof SourcingPartnersRoute
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commissions': {
      id: '/commissions'
      path: '/commissions'
      fullPath: '/commissions'
      preLoaderRoute: typeof CommissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disbursements': {
      id: '/disbursements'
      path: '/disbursements'
      fullPath: '/disbursements'
      preLoaderRoute: typeof DisbursementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sanctions': {
      id: '/sanctions'
      path: '/sanctions'
      fullPath: '/sanctions'
      preLoaderRoute: typeof SanctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sourcing-partners': {
      id: '/sourcing-partners'
      path: '/sourcing-partners'
      fullPath: '/sourcing-partners'
      preLoaderRoute: typeof SourcingPartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsRoute: ApplicationsRoute,
  CommissionsRoute: CommissionsRoute,
  DisbursementsRoute: DisbursementsRoute,
  LeadsRoute: LeadsRoute,
  ReportsRoute: ReportsRoute,
  SanctionsRoute: SanctionsRoute,
  SettingsRoute: SettingsRoute,
  SourcingPartnersRoute: SourcingPartnersRoute,
  TeamRoute: TeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
